version: '3'

services:
  key-value-store:
    build: .build/docker
    image: laravel-blog
    container_name: laravel_app
    depends_on:
      - mysql
      - redis
    volumes:
      - ./:/application:cached

  mysql:
    image: mysql:8
    container_name: laravel_app_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=key-value-store
    volumes:
      - db-data:/var/lib/mysql:cached

  nginx:
    image: nginx:alpine
    container_name: laravel_app_nginx
    ports:
      - "8000:8000"
    volumes:
      - .build/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
    depends_on:
      - key-value-store

  redis:
    image: redis:alpine
    container_name: laravel_app_redis
    ports:
      - "6380:6379"

volumes:
  db-data:
